import type { Reference } from '../../../../darwin-MFC/lib/types/references'

export const localReferences: Record<string, Reference> = {
  'acg-gerd-2022': {
    id: 'acg-gerd-2022',
    type: 'diretriz',
    title: 'ACG Clinical Guideline for the Diagnosis and Management of Gastroesophageal Reflux Disease',
    journal: 'The American Journal of Gastroenterology',
    year: 2022,
    volume: '117',
    pages: '27-56',
    doi: '10.14309/ajg.0000000000001538',
    authors: ['Katz PO', 'Dunbar KB', 'Schnoll-Sussman FH', 'Greer KB', 'Yadlapati R', 'Spechler SJ', 'et al'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/34807007/',
    accessDate: '2026-02-14',
    publisher: 'American College of Gastroenterology',
  },
  'acg-sii-2021': {
    id: 'acg-sii-2021',
    type: 'diretriz',
    title: 'ACG Clinical Guideline: Management of Irritable Bowel Syndrome',
    journal: 'The American Journal of Gastroenterology',
    year: 2021,
    volume: '116',
    pages: '17-44',
    doi: '10.14309/ajg.0000000000001036',
    authors: ['Lacy BE', 'Pimentel M', 'Brenner DM', 'Chey WD', 'Keefer LA', 'Long MD', 'et al'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/33315591/',
    accessDate: '2026-02-14',
    publisher: 'American College of Gastroenterology',
  },
  'aria-2020': {
    id: 'aria-2020',
    type: 'artigo',
    title:
      'Next-generation Allergic Rhinitis and Its Impact on Asthma (ARIA) guidelines for allergic rhinitis based on GRADE and real-world evidence',
    journal: 'Journal of Allergy and Clinical Immunology',
    year: 2020,
    volume: '145',
    pages: '70-80.e3',
    doi: '10.1016/j.jaci.2019.06.049',
    authors: ['Bousquet J', 'Schünemann HJ', 'Togias A', 'Bachert C', 'et al'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/31627910/',
    accessDate: '2026-02-14',
  },
  'gina-2024': {
    id: 'gina-2024',
    type: 'diretriz',
    title: 'Global Strategy for Asthma Management and Prevention (GINA 2024 update)',
    year: 2024,
    authors: ['Global Initiative for Asthma (GINA)'],
    publisher: 'GINA',
    url: 'https://ginasthma.org/2024-report/',
    accessDate: '2026-02-14',
  },
  'nice-depression-2022': {
    id: 'nice-depression-2022',
    type: 'diretriz',
    title: 'Depression in adults: treatment and management (NICE guideline NG222)',
    year: 2022,
    authors: ['National Institute for Health and Care Excellence (NICE)'],
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/ng222',
    accessDate: '2026-02-14',
  },
  'sbc-has-2020': {
    id: 'sbc-has-2020',
    type: 'diretriz',
    title: 'Diretrizes Brasileiras de Hipertensão Arterial – 2020',
    journal: 'Arquivos Brasileiros de Cardiologia',
    year: 2021,
    doi: '10.36660/abc.20201238',
    url: 'https://abccardiol.org/article/diretrizes-brasileiras-de-hipertensao-arterial-2020/',
    accessDate: '2026-02-14',
    authors: [
      'Barroso WKS',
      'Rodrigues CIS',
      'Bortolotto LA',
      'Mota-Gomes MA',
      'Brandão AA',
      'Feitosa ADM',
      'Kuschnir MCC',
      'et al',
    ],
    publisher: 'Sociedade Brasileira de Cardiologia (SBC)',
    note: 'Diretriz intitulada “2020” com publicação em 2021 no Arq Bras Cardiol (vol 116, n 3, p 516-658).',
  },
  'vigitel-2023': {
    id: 'vigitel-2023',
    type: 'relatorio',
    title:
      'Vigitel Brasil 2023: Vigilância de Fatores de Risco e Proteção para Doenças Crônicas por Inquérito Telefônico',
    year: 2023,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/vigitel/vigitel-brasil-2023-vigilancia-de-fatores-de-risco-e-protecao-para-doencas-cronicas-por-inquerito-telefonico/%40%40download/file',
    accessDate: '2026-02-14',
  },
  'dsm-5': {
    id: 'dsm-5',
    type: 'livro',
    title: 'Diagnostic and Statistical Manual of Mental Disorders: DSM-5 (5th ed.)',
    year: 2013,
    authors: ['American Psychiatric Association'],
    publisher: 'American Psychiatric Association',
    url: 'https://www.ncbi.nlm.nih.gov/nlmcatalog/101604226',
    accessDate: '2026-02-14',
    doi: '10.1176/appi.books.9780890425596',
    note: 'Metadados e ISBN disponíveis no NLM Catalog (NCBI).',
  },
  'rome-iv-2016': {
    id: 'rome-iv-2016',
    type: 'artigo',
    title: 'Functional Gastrointestinal Disorders: History, Pathophysiology, Clinical Features and Rome IV',
    journal: 'Gastroenterology',
    year: 2016,
    doi: '10.1053/j.gastro.2016.02.032',
    authors: ['Drossman DA'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/27144617/',
    accessDate: '2026-02-14',
  },
  'sbem-tireoide-2023': {
    id: 'sbem-tireoide-2023',
    type: 'diretriz',
    title: 'Consensos de Tireoide — Departamento de Tireoide (SBEM)',
    year: 2013,
    authors: ['Sociedade Brasileira de Endocrinologia e Metabologia (SBEM)'],
    publisher: 'SBEM — Departamento de Tireoide',
    url: 'https://www.endocrino.org.br/consensos-de-tireoide/',
    accessDate: '2026-02-14',
    note:
      'Página institucional que reúne os consensos brasileiros de tireoide publicados nos Arquivos Brasileiros de Endocrinologia e Metabologia (edição especial de 2013).',
  },
  'sbem-hipotireoidismo-especiais-2022': {
    id: 'sbem-hipotireoidismo-especiais-2022',
    type: 'diretriz',
    title:
      'Approach to adult patients with primary hypothyroidism in some special situations: a position statement from the Thyroid Department of the Brazilian Society of Endocrinology and Metabolism (SBEM)',
    journal: 'Archives of Endocrinology and Metabolism',
    year: 2022,
    volume: '66',
    pages: '871-882',
    doi: '10.20945/2359-3997000000545',
    authors: ['Mazeto GMF', 'Sgarbi JA', 'Ramos HE', 'Villagelin Neto DGP', 'Nogueira CR', 'Vaisman M', 'Graf H', 'de Carvalho GA'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/36394484/',
    accessDate: '2026-02-14',
    publisher: 'Sociedade Brasileira de Endocrinologia e Metabologia (SBEM) — Departamento de Tireoide',
    note:
      'Position statement da SBEM (Departamento de Tireoide) sobre abordagem do hipotireoidismo primário em situações especiais.',
  },
  'sbem-hipotireoidismo-subclinico-2013': {
    id: 'sbem-hipotireoidismo-subclinico-2013',
    type: 'diretriz',
    title:
      'The Brazilian consensus for the clinical approach and treatment of subclinical hypothyroidism in adults: recommendations of the Thyroid Department of the Brazilian Society of Endocrinology and Metabolism',
    journal: 'Arquivos Brasileiros de Endocrinologia e Metabologia',
    year: 2013,
    volume: '57',
    pages: '166-183',
    doi: '10.1590/S0004-27302013000300003',
    authors: ['Sgarbi JA', 'Teixeira PFS', 'Maciel LMZ', 'Mazeto GMFS', 'Vaisman M', 'Montenegro Junior RM', 'Ward LS'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/23681263/',
    accessDate: '2026-02-14',
    publisher: 'Sociedade Brasileira de Endocrinologia e Metabologia (SBEM) — Departamento de Tireoide',
    note: 'Consenso brasileiro (SBEM) para abordagem e tratamento do hipotireoidismo subclínico em adultos.',
  },
  'rename-2024': {
    id: 'rename-2024',
    type: 'relatorio',
    title: 'Relação Nacional de Medicamentos Essenciais (RENAME) 2024',
    year: 2024,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/composicao/sectics/rename',
    accessDate: '2026-02-14',
    note:
      'Portal oficial da RENAME (atualizada a cada 2 anos), com acesso à “Rename em Tempo Real” e publicações anteriores.',
  },
  'sbd-2024': {
    id: 'sbd-2024',
    type: 'diretriz',
    title: 'Diretrizes da Sociedade Brasileira de Diabetes 2024',
    year: 2024,
    authors: ['Sociedade Brasileira de Diabetes (SBD)'],
    publisher: 'Sociedade Brasileira de Diabetes (SBD)',
    doi: '10.29327/5412848',
    url: 'https://diretriz.diabetes.org.br/',
    accessDate: '2026-02-14',
    note: 'Diretriz SBD 2024 (ISBN 978-65-272-0704-7, conforme site oficial).',
  },
  'ada-2024': {
    id: 'ada-2024',
    type: 'diretriz',
    title: 'Introduction and Methodology: Standards of Care in Diabetes—2024',
    journal: 'Diabetes Care',
    year: 2024,
    volume: '47',
    pages: 'S1-S4',
    doi: '10.2337/dc24-SINT',
    authors: ['American Diabetes Association Professional Practice Committee'],
    publisher: 'American Diabetes Association (ADA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/38368515/',
    accessDate: '2026-02-14',
    note: 'Artigo introdutório do suplemento “Standards of Care in Diabetes—2024” (Diabetes Care, Supplement 1).',
  },
  'ada-diabetes-2024': {
    id: 'ada-diabetes-2024',
    type: 'diretriz',
    title: 'Standards of Care in Diabetes—2024',
    journal: 'Diabetes Care',
    year: 2024,
    volume: '47 (Supplement 1)',
    pages: 'S1-S350',
    authors: ['American Diabetes Association Professional Practice Committee'],
    publisher: 'American Diabetes Association (ADA)',
    url: 'https://diabetesjournals.org/care/issue/47/Supplement_1',
    accessDate: '2026-02-14',
    note: 'Página do suplemento completo (issue) da Diabetes Care para as Standards of Care 2024.',
  },
  'cdc-sti-2021': {
    id: 'cdc-sti-2021',
    type: 'diretriz',
    title: 'Sexually Transmitted Infections Treatment Guidelines, 2021',
    journal: 'MMWR Recommendations and Reports',
    year: 2021,
    volume: '70',
    pages: '1-187',
    doi: '10.15585/mmwr.rr7004a1',
    authors: ['Workowski KA', 'Bachmann LH', 'Chan PA', 'Johnston CM', 'Muzny CA', 'Park I', 'et al'],
    publisher: 'Centers for Disease Control and Prevention (CDC)',
    url: 'https://www.cdc.gov/std/treatment-guidelines/default.htm',
    accessDate: '2026-02-14',
  },
  'idsa-itu-2011': {
    id: 'idsa-itu-2011',
    type: 'diretriz',
    title:
      'International clinical practice guidelines for the treatment of acute uncomplicated cystitis and pyelonephritis in women: A 2010 update by the Infectious Diseases Society of America and the European Society for Microbiology and Infectious Diseases',
    journal: 'Clinical Infectious Diseases',
    year: 2011,
    volume: '52',
    pages: 'e103-e120',
    doi: '10.1093/cid/ciq257',
    authors: ['Gupta K', 'Hooton TM', 'Naber KG', 'Wullt B', 'Colgan R', 'Miller LG', 'et al'],
    publisher: 'Infectious Diseases Society of America (IDSA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/21292654/',
    accessDate: '2026-02-14',
  },
  'ichd-3': {
    id: 'ichd-3',
    type: 'diretriz',
    title:
      'Headache Classification Committee of the International Headache Society (IHS) The International Classification of Headache Disorders, 3rd edition',
    journal: 'Cephalalgia',
    year: 2018,
    volume: '38',
    pages: '1-211',
    doi: '10.1177/0333102417738202',
    authors: ['Headache Classification Committee of the International Headache Society (IHS)'],
    publisher: 'International Headache Society (IHS)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29368949/',
    accessDate: '2026-02-14',
  },
  'aha-stroke-2019': {
    id: 'aha-stroke-2019',
    type: 'diretriz',
    title:
      'Guidelines for the Early Management of Patients With Acute Ischemic Stroke: 2019 Update to the 2018 Guidelines for the Early Management of Acute Ischemic Stroke: A Guideline for Healthcare Professionals From the American Heart Association/American Stroke Association',
    journal: 'Stroke',
    year: 2019,
    volume: '50',
    pages: 'e344-e418',
    doi: '10.1161/STR.0000000000000211',
    authors: ['Powers WJ', 'Rabinstein AA', 'Ackerson T', 'Adeoye OM', 'Bambakidis NC', 'Becker K', 'et al'],
    publisher: 'American Heart Association / American Stroke Association (AHA/ASA)',
    url: 'https://professional.heart.org/en/science-news/2019-update-to-the-2018-acute-ischemic-stroke-guidelines/top-things-to-know',
    accessDate: '2026-02-14',
    note: 'Página institucional da AHA/ASA com resumo (“Top things to know”) da atualização 2019.',
  },
  'canmat-2024': {
    id: 'canmat-2024',
    type: 'diretriz',
    title:
      'Canadian Network for Mood and Anxiety Treatments (CANMAT) 2023 Update on Clinical Guidelines for Management of Major Depressive Disorder in Adults: Evidence Review and Recommendations',
    journal: 'The Canadian Journal of Psychiatry',
    year: 2024,
    volume: '69',
    pages: '641-687',
    doi: '10.1177/07067437241245384',
    authors: ['Lam RW', 'Kennedy SH', 'Milev R', 'Baldwin DS', 'Ramasubbu R', 'Parikh SV', 'et al'],
    publisher: 'Canadian Network for Mood and Anxiety Treatments (CANMAT)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/38711351/',
    accessDate: '2026-02-14',
    note: 'Diretriz CANMAT (update 2023) com publicação em 2024 no Canadian Journal of Psychiatry.',
  },
  'dsm5-tr': {
    id: 'dsm5-tr',
    type: 'livro',
    title: 'Diagnostic and Statistical Manual of Mental Disorders: DSM-5-TR (Text Revision)',
    year: 2022,
    authors: ['American Psychiatric Association'],
    publisher: 'American Psychiatric Association',
    doi: '10.1176/appi.books.9780890425787',
    url: 'https://dsm.psychiatryonline.org/doi/book/10.1176/appi.books.9780890425787',
    accessDate: '2026-02-14',
    note: 'Página oficial (pode exigir acesso institucional).',
  },
  'diretriz-dislipidemia-2023': {
    id: 'diretriz-dislipidemia-2023',
    type: 'diretriz',
    title:
      'Protocolo Clínico e Diretrizes Terapêuticas (PCDT): Dislipidemia — prevenção de eventos cardiovasculares e pancreatite',
    year: 2023,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil) / CONITEC',
    url: 'https://www.gov.br/conitec/pt-br/midias/protocolos/pcdt_dislipidemia.pdf/view',
    accessDate: '2026-02-14',
    note: 'PCDT com atualização publicada em 25/09/2023 na CONITEC (consulta do PDF na página oficial).',
  },
  'lancet-lombalgia-2018': {
    id: 'lancet-lombalgia-2018',
    type: 'artigo',
    title: 'What low back pain is and why we need to pay attention',
    journal: 'The Lancet',
    year: 2018,
    volume: '391',
    pages: '2356-2367',
    doi: '10.1016/S0140-6736(18)30480-X',
    authors: ['Hartvigsen J', 'Hancock MJ', 'Kongsted A', 'Louw Q', 'Ferreira ML', 'Genevay S', 'et al'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/29573870/',
    accessDate: '2026-02-14',
  },
  'aasm-insonia-2017': {
    id: 'aasm-insonia-2017',
    type: 'diretriz',
    title: 'Clinical practice guideline for the pharmacologic treatment of chronic insomnia in adults: an American Academy of Sleep Medicine clinical practice guideline',
    journal: 'Journal of Clinical Sleep Medicine',
    year: 2017,
    volume: '13',
    pages: '307-349',
    doi: '10.5664/jcsm.6470',
    authors: ['Sateia MJ', 'Buysse DJ', 'Krystal AD', 'Neubauer DN', 'Heald JL'],
    publisher: 'American Academy of Sleep Medicine (AASM)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27998379/',
    accessDate: '2026-02-14',
  },
  'oarsi-2019': {
    id: 'oarsi-2019',
    type: 'diretriz',
    title: 'OARSI guidelines for the non-surgical management of knee, hip, and polyarticular osteoarthritis',
    journal: 'Osteoarthritis and Cartilage',
    year: 2019,
    volume: '27',
    pages: '1578-1589',
    doi: '10.1016/j.joca.2019.06.011',
    authors: ['Bannuru RR', 'Osani MC', 'Vaysbrot EE', 'Arden NK', 'Bierma-Zeinstra SMA', 'Kraus VB', 'et al'],
    publisher: 'Osteoarthritis Research Society International (OARSI)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31278997/',
    accessDate: '2026-02-14',
  },
  'acg-dispepsia-2022': {
    id: 'acg-dispepsia-2022',
    type: 'diretriz',
    title: 'ACG and CAG Clinical Guideline: Management of Dyspepsia',
    journal: 'The American Journal of Gastroenterology',
    year: 2017,
    volume: '112',
    pages: '988-1013',
    doi: '10.1038/ajg.2017.154',
    authors: ['Moayyedi PM', 'Lacy BE', 'Andrews CN', 'Enns RA', 'Howden CW', 'Vakil N'],
    publisher: 'American College of Gastroenterology (ACG)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28631728/',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; a diretriz ACG/CAG amplamente citada é de 2017 (AJG).',
  },
  'acr-gout-2020': {
    id: 'acr-gout-2020',
    type: 'diretriz',
    title: '2020 American College of Rheumatology Guideline for the Management of Gout',
    journal: 'Arthritis Care & Research',
    year: 2020,
    volume: '72',
    pages: '744-760',
    doi: '10.1002/acr.24180',
    authors: ['FitzGerald JD', 'Dalbeth N', 'Mikuls T', 'Brignardello-Petersen R', 'Guyatt G', 'Abeles AM', 'et al'],
    publisher: 'American College of Rheumatology (ACR)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32391934/',
    accessDate: '2026-02-14',
  },
  'mds-pd-2015': {
    id: 'mds-pd-2015',
    type: 'diretriz',
    title: "MDS clinical diagnostic criteria for Parkinson's disease",
    journal: 'Movement Disorders',
    year: 2015,
    volume: '30',
    pages: '1591-1601',
    doi: '10.1002/mds.26424',
    authors: ['Postuma RB', 'Berg D', 'Stern M', 'Poewe W', 'Olanow CW', 'Oertel W', 'et al'],
    publisher: 'International Parkinson and Movement Disorder Society (MDS)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26474316/',
    accessDate: '2026-02-14',
  },
  'sepsis-3': {
    id: 'sepsis-3',
    type: 'artigo',
    title: 'The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3)',
    journal: 'JAMA',
    year: 2016,
    volume: '315',
    pages: '801-810',
    doi: '10.1001/jama.2016.0287',
    authors: ['Singer M', 'Deutschman CS', 'Seymour CW', 'Shankar-Hari M', 'Annane D', 'Bauer M', 'et al'],
    url: 'https://pubmed.ncbi.nlm.nih.gov/26903338/',
    accessDate: '2026-02-14',
  },
  'surviving-sepsis-2021': {
    id: 'surviving-sepsis-2021',
    type: 'diretriz',
    title: 'Surviving Sepsis Campaign: International Guidelines for Management of Sepsis and Septic Shock 2021',
    journal: 'Critical Care Medicine',
    year: 2021,
    volume: '49',
    pages: 'e1063-e1143',
    doi: '10.1097/CCM.0000000000005337',
    authors: ['Evans L', 'Rhodes A', 'Alhazzani W', 'Antonelli M', 'Coopersmith CM', 'French C', 'et al'],
    publisher: 'Surviving Sepsis Campaign',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34605781/',
    accessDate: '2026-02-14',
  },
  'gold-2024': {
    id: 'gold-2024',
    type: 'diretriz',
    title: 'Global Strategy for the Diagnosis, Management, and Prevention of Chronic Obstructive Pulmonary Disease (GOLD 2024 Report)',
    year: 2024,
    authors: ['Global Initiative for Chronic Obstructive Lung Disease (GOLD)'],
    publisher: 'GOLD',
    url: 'https://goldcopd.org/2024-gold-report-2/',
    accessDate: '2026-02-14',
  },
  'kdigo-ckd-2024': {
    id: 'kdigo-ckd-2024',
    type: 'diretriz',
    title: 'KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease',
    year: 2024,
    authors: ['Kidney Disease: Improving Global Outcomes (KDIGO)'],
    publisher: 'KDIGO',
    url: 'https://kdigo.org/wp-content/uploads/2024/03/KDIGO-2024-CKD-Guideline.pdf',
    accessDate: '2026-02-14',
  },
  'eshre-pcos-2023': {
    id: 'eshre-pcos-2023',
    type: 'diretriz',
    title: 'International evidence-based guideline for the assessment and management of polycystic ovary syndrome, 2023',
    year: 2023,
    publisher: 'European Society of Human Reproduction and Embryology (ESHRE)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/37036934/',
    accessDate: '2026-02-14',
  },
  'eau-bph-2023': {
    id: 'eau-bph-2023',
    type: 'diretriz',
    title: 'EAU Guidelines on the Management of Non-neurogenic Male Lower Urinary Tract Symptoms (LUTS), including Benign Prostatic Obstruction (BPO)',
    year: 2023,
    authors: ['European Association of Urology (EAU)'],
    publisher: 'European Association of Urology (EAU)',
    url: 'https://uroweb.org/guidelines/management-of-non-neurogenic-male-luts',
    accessDate: '2026-02-14',
  },
  'eau-urolithiasis-2023': {
    id: 'eau-urolithiasis-2023',
    type: 'diretriz',
    title: 'EAU Guidelines on Urolithiasis',
    year: 2023,
    authors: ['European Association of Urology (EAU)'],
    publisher: 'European Association of Urology (EAU)',
    url: 'https://uroweb.org/guidelines/urolithiasis',
    accessDate: '2026-02-14',
  },
  'wao-anaphylaxis-2020': {
    id: 'wao-anaphylaxis-2020',
    type: 'diretriz',
    title: 'World Allergy Organization Anaphylaxis Guidance 2020',
    journal: 'World Allergy Organization Journal',
    year: 2020,
    volume: '13',
    pages: '100472',
    doi: '10.1016/j.waojou.2020.100472',
    authors: ['Cardona V', 'Ansotegui IJ', 'Ebisawa M', 'El-Gamal Y', 'Fernandez Rivas M', 'Fineman S', 'et al'],
    publisher: 'World Allergy Organization (WAO)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32792413/',
    accessDate: '2026-02-14',
  },
  'eaaci-anaphylaxis-2021': {
    id: 'eaaci-anaphylaxis-2021',
    type: 'diretriz',
    title: 'EAACI guideline: Anaphylaxis (2021 update)',
    journal: 'Allergy',
    year: 2021,
    doi: '10.1111/all.15032',
    authors: ['Muraro A', 'Worm M', 'Alviani C', 'Cardona V', 'DunnGalvin A', 'Garvey LH', 'et al'],
    publisher: 'European Academy of Allergy and Clinical Immunology (EAACI)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34478586/',
    accessDate: '2026-02-14',
  },
  'asbai-anafilaxia-2022': {
    id: 'asbai-anafilaxia-2022',
    type: 'diretriz',
    title:
      'Brazilian guideline on anaphylaxis: Part 1. Epidemiology, risk factors, classification, and diagnosis',
    journal: 'The Journal of Allergy and Clinical Immunology: In Practice',
    year: 2022,
    doi: '10.1016/j.jaip.2022.01.014',
    authors: ['Castro FFM', 'Antunes A', 'Kleinheinz A', 'Farias R', 'Ribeiro M', 'Ensina LF', 'et al'],
    publisher: 'Associação Brasileira de Alergia e Imunologia (ASBAI)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35202769/',
    accessDate: '2026-02-14',
  },
  'ilas-sepse-2023': {
    id: 'ilas-sepse-2023',
    type: 'diretriz',
    title: 'Campanha Sobrevivendo à Sepse (ILAS) — Protocolo Gerenciado 2023',
    year: 2023,
    authors: ['Instituto Latino-Americano de Sepse (ILAS)'],
    publisher: 'Instituto Latino-Americano de Sepse (ILAS)',
    url: 'https://ilas.org.br/assets/arquivos/upload/ILAS2023_CampanhaSobrevivendoSepseProtocoloGerenciado.pdf',
    accessDate: '2026-02-14',
  },
  'ms-cab-37-2013': {
    id: 'ms-cab-37-2013',
    type: 'relatorio',
    title: 'Cadernos de Atenção Básica, n. 37: Estratégias para o cuidado da pessoa com doença crônica — Hipertensão arterial sistêmica',
    year: 2013,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'http://bvsms.saude.gov.br/bvs/publicacoes/estrategias_cuidado_pessoa_doenca_cronica.pdf',
    accessDate: '2026-02-14',
    note: 'Caderno de Atenção Básica (CAB) do Ministério da Saúde voltado ao cuidado na APS.',
  },
  'who-depression-2023': {
    id: 'who-depression-2023',
    type: 'site',
    title: 'Depression',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/depression',
    accessDate: '2026-02-14',
  },
  'who-anemia-2023': {
    id: 'who-anemia-2023',
    type: 'site',
    title: 'Anaemia',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/anaemia',
    accessDate: '2026-02-14',
  },
  'who-malaria-2023': {
    id: 'who-malaria-2023',
    type: 'site',
    title: 'Malaria',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/malaria',
    accessDate: '2026-02-14',
  },
  'who-chagas-2023': {
    id: 'who-chagas-2023',
    type: 'site',
    title: 'Chagas disease (American trypanosomiasis)',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/health-topics/chagas-disease',
    accessDate: '2026-02-14',
  },
  'who-leishmaniasis-2023': {
    id: 'who-leishmaniasis-2023',
    type: 'site',
    title: 'Leishmaniasis',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/health-topics/leishmaniasis',
    accessDate: '2026-02-14',
  },
  'who-leptospirosis-2023': {
    id: 'who-leptospirosis-2023',
    type: 'site',
    title: 'Leptospirosis',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/leptospirosis',
    accessDate: '2026-02-14',
  },
  'who-yellowfever-2023': {
    id: 'who-yellowfever-2023',
    type: 'site',
    title: 'Yellow fever',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/yellow-fever',
    accessDate: '2026-02-14',
  },
  'who-schistosomiasis-2023': {
    id: 'who-schistosomiasis-2023',
    type: 'site',
    title: 'Schistosomiasis',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/schistosomiasis',
    accessDate: '2026-02-14',
  },
  'who-leprosy-2023': {
    id: 'who-leprosy-2023',
    type: 'site',
    title: 'Leprosy',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/leprosy',
    accessDate: '2026-02-14',
  },
  'who-rabies-2023': {
    id: 'who-rabies-2023',
    type: 'site',
    title: 'Rabies',
    year: 2023,
    authors: ['World Health Organization (WHO)'],
    publisher: 'World Health Organization (WHO)',
    url: 'https://www.who.int/news-room/fact-sheets/detail/rabies',
    accessDate: '2026-02-14',
  },
  'diretriz-ic-2021': {
    id: 'diretriz-ic-2021',
    type: 'diretriz',
    title: '2021 Focused Update of the Brazilian Guideline of Chronic and Acute Heart Failure: Diagnosis and Treatment',
    journal: 'Arquivos Brasileiros de Cardiologia',
    year: 2021,
    doi: '10.36660/abc.20210333',
    authors: ['Rocha RM', 'Bocchi EA', 'Cardoso JN', 'Albuquerque DC', 'Baumworcel L', 'et al'],
    publisher: 'Sociedade Brasileira de Cardiologia (SBC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35997670/',
    accessDate: '2026-02-14',
    note: 'Diretriz intitulada “2021” com publicação em 2022 no Arq Bras Cardiol (ePub 2022).',
  },
  'esc-fa-2020': {
    id: 'esc-fa-2020',
    type: 'diretriz',
    title:
      '2020 ESC Guidelines for the diagnosis and management of atrial fibrillation developed in collaboration with the European Association for Cardio-Thoracic Surgery (EACTS)',
    journal: 'European Heart Journal',
    year: 2020,
    doi: '10.1093/eurheartj/ehaa612',
    authors: ['Hindricks G', 'Potpara T', 'Dagres N', 'Arbelo E', 'Bax JJ', 'Blomström-Lundqvist C', 'et al'],
    publisher: 'European Society of Cardiology (ESC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32860505/',
    accessDate: '2026-02-14',
  },
  'esc-dac-2019': {
    id: 'esc-dac-2019',
    type: 'diretriz',
    title: '2019 ESC Guidelines for the diagnosis and management of chronic coronary syndromes',
    journal: 'European Heart Journal',
    year: 2019,
    doi: '10.1093/eurheartj/ehz425',
    authors: ['Knuuti J', 'Wijns W', 'Saraste A', 'Capodanno D', 'Barbato E', 'Funck-Brentano C', 'et al'],
    publisher: 'European Society of Cardiology (ESC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31504439/',
    accessDate: '2026-02-14',
  },
  'esc-hf-2021': {
    id: 'esc-hf-2021',
    type: 'diretriz',
    title: '2021 ESC Guidelines for the diagnosis and treatment of acute and chronic heart failure',
    journal: 'European Heart Journal',
    year: 2021,
    doi: '10.1093/eurheartj/ehab368',
    authors: ['McDonagh TA', 'Metra M', 'Adamo M', 'Gardner RS', 'Baumbach A', 'Böhm M', 'et al'],
    publisher: 'European Society of Cardiology (ESC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34447992/',
    accessDate: '2026-02-14',
  },
  'esc-stemi-2023': {
    id: 'esc-stemi-2023',
    type: 'diretriz',
    title: '2023 ESC Guidelines for the management of acute coronary syndromes in patients presenting with ST-segment elevation',
    journal: 'European Heart Journal',
    year: 2023,
    doi: '10.1093/eurheartj/ehad191',
    authors: ['Ibanez B', 'James S', 'Agewall S', 'Antunes MJ', 'Buccheri S', 'Bojek M', 'et al'],
    publisher: 'European Society of Cardiology (ESC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/37622666/',
    accessDate: '2026-02-14',
  },
  'sbc-sca-2020': {
    id: 'sbc-sca-2020',
    type: 'diretriz',
    title: 'Diretriz Brasileira de Síndrome Coronariana Aguda',
    journal: 'Arquivos Brasileiros de Cardiologia',
    year: 2021,
    doi: '10.36660/abc.20210180',
    authors: ['Nicolau JC', 'Feitosa Filho GS', 'Piegas LS', 'Marin-Neto JA', 'Rassi A Jr', 'et al'],
    publisher: 'Sociedade Brasileira de Cardiologia (SBC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34890282/',
    accessDate: '2026-02-14',
    note: 'Diretriz intitulada “SCA 2020” com publicação em 2021 no Arq Bras Cardiol.',
  },
  'aha-ua-nstemi-2021': {
    id: 'aha-ua-nstemi-2021',
    type: 'diretriz',
    title: '2021 AHA/ACC/ASE/CHEST/SAEM/SCCT/SCMR Guideline for the Evaluation and Diagnosis of Chest Pain',
    journal: 'Circulation',
    year: 2021,
    doi: '10.1161/CIR.0000000000001029',
    authors: ['Gulati M', 'Levy PD', 'Mukherjee D', 'Amsterdam E', 'Bhatt DL', 'Birtcher KK', 'et al'],
    publisher: 'American Heart Association / American College of Cardiology (AHA/ACC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34709879/',
    accessDate: '2026-02-14',
    note: 'RefId no darwin-MFC sugere UA/NSTEMI; a diretriz AHA/ACC 2021 mais diretamente relacionada é a de avaliação de dor torácica.',
  },
  'sbn-avc-2022': {
    id: 'sbn-avc-2022',
    type: 'diretriz',
    title: 'Guidelines for acute ischemic stroke treatment: part II: stroke treatment',
    journal: 'Arquivos de Neuro-Psiquiatria',
    year: 2022,
    doi: '10.1055/s-0042-1758976',
    authors: ['Martins SCO', 'Pontes-Neto OM', 'Albuquerque DC', 'et al'],
    publisher: 'Academia Brasileira de Neurologia (ABN) / Sociedade Brasileira de Neurologia (SBN)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/36237366/',
    accessDate: '2026-02-14',
  },
  'eso-stroke-2021': {
    id: 'eso-stroke-2021',
    type: 'diretriz',
    title: 'European Stroke Organisation (ESO) guidelines on intravenous thrombolysis for acute ischaemic stroke',
    journal: 'European Stroke Journal',
    year: 2021,
    authors: ['European Stroke Organisation (ESO)'],
    publisher: 'European Stroke Organisation (ESO)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34268125/',
    accessDate: '2026-02-14',
  },
  'idsa-pharyngitis-2012': {
    id: 'idsa-pharyngitis-2012',
    type: 'diretriz',
    title:
      'Clinical Practice Guideline for the Diagnosis and Management of Group A Streptococcal Pharyngitis: 2012 Update by the Infectious Diseases Society of America',
    journal: 'Clinical Infectious Diseases',
    year: 2012,
    doi: '10.1093/cid/cis629',
    authors: ['Shulman ST', 'Bisno AL', 'Clegg HW', 'Gerber MA', 'Kaplan EL', 'Lee G', 'et al'],
    publisher: 'Infectious Diseases Society of America (IDSA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/22965026/',
    accessDate: '2026-02-14',
  },
  'acr-fibro-2016': {
    id: 'acr-fibro-2016',
    type: 'artigo',
    title: '2016 Revisions to the 2010/2011 fibromyalgia diagnostic criteria',
    journal: 'Arthritis Care & Research',
    year: 2016,
    doi: '10.1002/acr.23273',
    authors: ['Wolfe F', 'Clauw DJ', 'Fitzcharles MA', 'Goldenberg DL', 'Häuser W', 'Katz RS', 'et al'],
    publisher: 'American College of Rheumatology (ACR)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27916278/',
    accessDate: '2026-02-14',
  },
  'eular-fibro-2017': {
    id: 'eular-fibro-2017',
    type: 'diretriz',
    title: 'EULAR revised recommendations for the management of fibromyalgia',
    journal: 'Annals of the Rheumatic Diseases',
    year: 2017,
    doi: '10.1136/annrheumdis-2016-209724',
    authors: ['Macfarlane GJ', 'Kronisch C', 'Atzeni F', 'Häuser W', 'Choy EH', 'Amris K', 'et al'],
    publisher: 'European Alliance of Associations for Rheumatology (EULAR)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27377815/',
    accessDate: '2026-02-14',
  },
  'eaaci-urt-2022': {
    id: 'eaaci-urt-2022',
    type: 'diretriz',
    title:
      'The international EAACI/GA2LEN/EuroGuiDerm/APAAACI guideline for the definition, classification, diagnosis, and management of urticaria',
    journal: 'Allergy',
    year: 2022,
    doi: '10.1111/all.15090',
    authors: ['Zuberbier T', 'Abuaf N', 'Bindslev-Jensen C', 'Canonica W', 'Church MK', 'Giménez-Arnau A', 'et al'],
    publisher: 'European Academy of Allergy and Clinical Immunology (EAACI)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34536239/',
    accessDate: '2026-02-14',
  },
  'ilae-2017': {
    id: 'ilae-2017',
    type: 'diretriz',
    title:
      'Operational classification of seizure types by the International League Against Epilepsy: Position Paper of the ILAE Commission for Classification and Terminology',
    journal: 'Epilepsia',
    year: 2017,
    doi: '10.1111/epi.13670',
    authors: ['Fisher RS', 'Cross JH', 'French JA', 'Higurashi N', 'Hirsch E', 'Jansen FE', 'et al'],
    publisher: 'International League Against Epilepsy (ILAE)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28276060/',
    accessDate: '2026-02-14',
  },
  'ilae-status-2015': {
    id: 'ilae-status-2015',
    type: 'diretriz',
    title:
      'A definition and classification of status epilepticus--Report of the ILAE Task Force on Classification of Status Epilepticus',
    journal: 'Epilepsia',
    year: 2015,
    doi: '10.1111/epi.13121',
    authors: ['Trinka E', 'Cock H', 'Hesdorffer D', 'Rossetti AO', 'Scheffer IE', 'Shinnar S', 'et al'],
    publisher: 'International League Against Epilepsy (ILAE)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26336950/',
    accessDate: '2026-02-14',
  },
  'bsh-b12-2014': {
    id: 'bsh-b12-2014',
    type: 'diretriz',
    title: 'Guidelines for the diagnosis and treatment of cobalamin and folate disorders',
    journal: 'British Journal of Haematology',
    year: 2014,
    doi: '10.1111/bjh.12959',
    authors: ['Devalia V', 'Hamilton MS', 'Moloy A'],
    publisher: 'British Society for Haematology (BSH)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/24942828/',
    accessDate: '2026-02-14',
  },
  'ash-itp-2019': {
    id: 'ash-itp-2019',
    type: 'diretriz',
    title: 'American Society of Hematology 2019 guidelines for immune thrombocytopenia',
    journal: 'Blood Advances',
    year: 2019,
    doi: '10.1182/bloodadvances.2019000966',
    authors: ['Neunert C', 'Terrell DR', 'Arnold DM', 'Buchanan G', 'Cines DB', 'Cooper N', 'et al'],
    publisher: 'American Society of Hematology (ASH)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31794604/',
    accessDate: '2026-02-14',
  },
  'acog-hyp-2020': {
    id: 'acog-hyp-2020',
    type: 'diretriz',
    title: 'Gestational Hypertension and Preeclampsia: ACOG Practice Bulletin, Number 222',
    journal: 'Obstetrics & Gynecology',
    year: 2020,
    doi: '10.1097/AOG.0000000000003891',
    authors: ['American College of Obstetricians and Gynecologists'],
    publisher: 'American College of Obstetricians and Gynecologists (ACOG)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32443079/',
    accessDate: '2026-02-14',
  },
  'aapcc-annual-report-2022': {
    id: 'aapcc-annual-report-2022',
    type: 'relatorio',
    title: "2022 Annual Report of the American Association of Poison Control Centers' National Poison Data System (NPDS): 40th Annual Report",
    journal: 'Clinical Toxicology',
    year: 2023,
    doi: '10.1080/15563650.2023.2268980',
    authors: ['Gummin DD', 'Mowry JB', 'Beuhler MC', 'Spyker DA', 'Brooks DE', 'Dibert KW', 'et al'],
    publisher: 'American Association of Poison Control Centers (AAPCC)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/37685579/',
    accessDate: '2026-02-14',
    note: 'Annual report “2022” com publicação em 2023 (Clinical Toxicology).',
  },
  'sbpt-pac-2022': {
    id: 'sbpt-pac-2022',
    type: 'diretriz',
    title: 'Diretrizes brasileiras para pneumonia adquirida na comunidade em adultos imunocompetentes - 2009',
    journal: 'Jornal Brasileiro de Pneumologia',
    year: 2009,
    volume: '35',
    pages: '574-601',
    doi: '10.1590/S1806-37132009000600011',
    authors: ['Corrêa RA', 'Lundgren FLC', 'Pereira-Silva JL', 'Frare e Silva RL', 'et al'],
    publisher: 'Sociedade Brasileira de Pneumologia e Tisiologia (SBPT)',
    url: 'https://jbp.org.br/details/1143/pt-BR',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; diretriz da SBPT publicada em 2009 no J Bras Pneumol.',
  },
  'abeso-2022': {
    id: 'abeso-2022',
    type: 'diretriz',
    title: 'Posicionamento sobre o tratamento nutricional do sobrepeso e da obesidade',
    year: 2022,
    authors: ['Associação Brasileira para o Estudo da Obesidade e da Síndrome Metabólica (ABESO)'],
    publisher: 'ABESO',
    url: 'https://abeso.org.br/wp-content/uploads/2022/11/posicionamento_2022-alterado-nov-22-1.pdf',
    accessDate: '2026-02-14',
  },
  'aad-ad-2022': {
    id: 'aad-ad-2022',
    type: 'diretriz',
    title: 'Atopic dermatitis clinical guideline (AAD)',
    year: 2022,
    authors: ['American Academy of Dermatology (AAD)'],
    publisher: 'American Academy of Dermatology (AAD)',
    url: 'https://www.aad.org/practicecenter/quality/clinical-guidelines/atopic-dermatitis/topical-therapy/topical-calcineurin-inhibitors-recommendations',
    accessDate: '2026-02-14',
    note:
      'Página institucional de guideline (inclui atualizações publicadas em 2022 e subsequentes).',
  },
  'aad-pso-2021': {
    id: 'aad-pso-2021',
    type: 'diretriz',
    title: 'Psoriasis clinical guideline (AAD)',
    year: 2021,
    authors: ['American Academy of Dermatology (AAD)'],
    publisher: 'American Academy of Dermatology (AAD)',
    url: 'https://www.aad.org/member/clinical-quality/guidelines/psoriasis',
    accessDate: '2026-02-14',
    note: 'Página institucional do guideline de psoríase (AAD).',
  },
  'ms-dengue-2024': {
    id: 'ms-dengue-2024',
    type: 'diretriz',
    title: 'Dengue: diagnóstico e manejo clínico: adulto e criança',
    year: 2024,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/dengue/dengue-diagnostico-e-manejo-clinico-adulto-e-crianca/view',
    accessDate: '2026-02-14',
  },
  'abs-cefaleia-2022': {
    id: 'abs-cefaleia-2022',
    type: 'diretriz',
    title: 'Consensus of the Brazilian Headache Society (SBCe) for the Prophylactic Treatment of Episodic Migraine: part I',
    journal: 'Arquivos de Neuro-Psiquiatria',
    year: 2022,
    volume: '80',
    pages: '845-861',
    doi: '10.1055/s-0042-1756441',
    authors: ['Melhado EM', 'Santos PSF', 'Kaup AO', 'et al'],
    publisher: 'Sociedade Brasileira de Cefaleia (SBCe)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/36252594/',
    accessDate: '2026-02-14',
    note:
      'Consenso publicado em partes. Parte II (Arq Neuropsiquiatr 2022;80(9):953-969) DOI: 10.1055/s-0042-1755320.',
  },
  'goldfrank-toxicology': {
    id: 'goldfrank-toxicology',
    type: 'livro',
    title: "Goldfrank's Toxicologic Emergencies",
    year: 2019,
    authors: ['Nelson LS', 'Howland MA', 'Lewin NA', 'Smith SW', 'Goldfrank LR', 'Hoffman RS', 'et al'],
    publisher: 'McGraw Hill Education',
    edition: '11th ed.',
    accessDate: '2026-02-14',
    note:
      'Obra de referência em toxicologia clínica; edição/ano podem variar conforme a versão consultada.',
  },
  'sbpt-intoxicacoes-2021': {
    id: 'sbpt-intoxicacoes-2021',
    type: 'site',
    title: 'Intoxicações exógenas (SBP)',
    year: 2024,
    authors: ['Sociedade Brasileira de Pediatria (SBP)'],
    publisher: 'Sociedade Brasileira de Pediatria (SBP)',
    url: 'https://www.sbp.com.br/pediatria-para-familias-2025/seguranca-e-prevencao/intoxicacoes-exogenas/',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2021” por compatibilidade com o darwin-MFC; página institucional atualizada em 2024.',
  },
  'sbq-queimaduras-2021': {
    id: 'sbq-queimaduras-2021',
    type: 'relatorio',
    title: 'Manual de Queimaduras para Estudantes',
    year: 2021,
    authors: ['Sociedade Brasileira de Queimaduras (SBQ)'],
    publisher: 'Sociedade Brasileira de Queimaduras (SBQ)',
    url: 'https://sbqueimaduras.org.br/material/3091',
    accessDate: '2026-02-14',
    note: 'Material gratuito disponibilizado pela SBQ (parceria com ESCS/DF).',
  },
  'aba-guidelines-2016': {
    id: 'aba-guidelines-2016',
    type: 'diretriz',
    title: 'Guidelines for Burn Care Under Austere Conditions: Introduction to Burn Disaster, Airway and Ventilator Management, and Fluid Resuscitation',
    journal: 'Journal of Burn Care & Research',
    year: 2016,
    volume: '37',
    pages: 'e427-e439',
    doi: '10.1097/BCR.0000000000000304',
    authors: ['Kearns RD', 'Conlon KM', 'Matherly AF', 'Chung KK', 'Bebarta VS', 'Hansen JJ', 'et al'],
    publisher: 'American Burn Association',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27224004/',
    accessDate: '2026-02-14',
  },
  'lbn-eme-2020': {
    id: 'lbn-eme-2020',
    type: 'livro',
    title: 'Atualização no estado de mal epiléptico',
    year: 2020,
    authors: ['Castro LHM'],
    publisher: 'Manole',
    url: 'https://repositorio.usp.br/item/003060156',
    accessDate: '2026-02-14',
    note: 'Capítulo em: Condutas em neurologia. ISBN: 9788520462157.',
  },
  'sbc-ic-2018': {
    id: 'sbc-ic-2018',
    type: 'diretriz',
    title: 'Diretriz Brasileira de Insuficiência Cardíaca Crônica e Aguda',
    journal: 'Arquivos Brasileiros de Cardiologia',
    year: 2018,
    volume: '111',
    pages: '436-539',
    doi: '10.5935/abc.20180190',
    authors: ['Rohde LEP', 'Montera MW', 'Bocchi EA', 'Clausell NO', 'Albuquerque DC', 'Rassi S', 'et al'],
    publisher: 'Sociedade Brasileira de Cardiologia (SBC) — DEIC',
    url: 'https://abccardiol.org/article/diretriz-brasileira-de-insuficiencia-cardiaca-cronica-eaguda/',
    accessDate: '2026-02-14',
  },
  'sbd-cad-2022': {
    id: 'sbd-cad-2022',
    type: 'diretriz',
    title: 'Diagnóstico e tratamento da Cetoacidose Diabética',
    year: 2023,
    authors: ['Santomauro AT', 'Santomauro AC Jr', 'Pessanha AB', 'Raduan RA', 'Marino EC', 'Lamounier RN'],
    publisher: 'Sociedade Brasileira de Diabetes (SBD)',
    doi: '10.29327/5238993.2023-6',
    url: 'https://diretriz.diabetes.org.br/diagnostico-e-tratamento-da-cetoacidose-diabetica/',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; conteúdo publicado em 2023 (com revisões posteriores).',
  },
  'ms-malaria-2022': {
    id: 'ms-malaria-2022',
    type: 'diretriz',
    title: 'Guia para Gestão Local do Controle da Malária - Diagnóstico e Tratamento',
    year: 2022,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/malaria/diagnostico-de-malaria/guia-para-gestao-local-do-controle-da-malaria-diagnostico-e-tratamento.pdf/view',
    accessDate: '2026-02-14',
  },
  'consenso-chagas-2016': {
    id: 'consenso-chagas-2016',
    type: 'diretriz',
    title: 'II Consenso Brasileiro em Doença de Chagas, 2015',
    journal: 'Epidemiologia e Serviços de Saúde',
    year: 2016,
    volume: '25 (número especial)',
    pages: '7-86',
    doi: '10.5123/S1679-49742016000500002',
    authors: ['Dias JCP', 'Ramos Jr AN', 'Gontijo ED', 'Luquetti A', 'Shikanai-Yasuda MA', 'Coura JR', 'et al'],
    publisher: 'Ministério da Saúde (Brasil) / Sociedade Brasileira de Medicina Tropical (SBMT)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27869914/',
    accessDate: '2026-02-14',
    note: 'Consenso brasileiro (2015) com publicação em 2016.',
  },
  'ms-lv-2022': {
    id: 'ms-lv-2022',
    type: 'diretriz',
    title: 'Manual de leishmaniose visceral: recomendações clínicas para a redução da letalidade',
    year: 2022,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/leishmaniose-visceral/manual-de-leishmaniose-visceral-recomendacoes-clinicas-para-a-reducao-da-letalidade/view',
    accessDate: '2026-02-14',
  },
  'ms-leptospirose-2022': {
    id: 'ms-leptospirose-2022',
    type: 'diretriz',
    title: 'Leptospirose - diagnóstico e manejo clínico',
    year: 2014,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/l/leptospirose/publicacoes/leptospirose-diagnostico-e-manejo-clinico-2014.pdf/view',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; manual originalmente publicado em 2014 e disponibilizado no gov.br (página atualizada em 2022).',
  },
  'ms-fa-2022': {
    id: 'ms-fa-2022',
    type: 'diretriz',
    title: 'Manual de Manejo Clínico da Febre Amarela',
    year: 2020,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/guias-e-manuais/2020/manual-manejo-clinico-febre-amarela-2020/view',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; página do manual (2020) com atualizações publicadas posteriormente.',
  },
  'ms-esquistossomose-2022': {
    id: 'ms-esquistossomose-2022',
    type: 'diretriz',
    title: 'Vigilância da Esquistossomose Mansoni: Diretrizes Técnicas',
    year: 2024,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/e/esquistossomose/publicacoes/vigilancia-da-esquistossomose-mansoni-2024.pdf/view',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2022” por compatibilidade com o darwin-MFC; diretriz técnica com atualização publicada em 2024 no gov.br.',
  },
  'ms-hanseniase-2022': {
    id: 'ms-hanseniase-2022',
    type: 'diretriz',
    title: 'Protocolo Clínico e Diretrizes Terapêuticas (PCDT) da Hanseníase',
    year: 2022,
    authors: ['Ministério da Saúde (Brasil) / CONITEC'],
    publisher: 'Ministério da Saúde (Brasil) / CONITEC',
    url: 'https://www.gov.br/conitec/pt-br/midias/protocolos/20220818_pcdt_hanseniase.pdf/view',
    accessDate: '2026-02-14',
    note: 'Aprovado por Portaria SCTIE/MS nº 67, de 7 de julho de 2022 (PCDT Hanseníase).',
  },
  'ms-raiva-2022': {
    id: 'ms-raiva-2022',
    type: 'diretriz',
    title: 'Normas Técnicas da Profilaxia da Raiva Humana',
    year: 2022,
    authors: ['Ministério da Saúde (Brasil)'],
    publisher: 'Ministério da Saúde (Brasil)',
    url: 'https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/svsa/raiva/normas-tecnicas-da-profilaxia-da-raiva-humana.pdf/view',
    accessDate: '2026-02-14',
  },
  'ata-2024': {
    id: 'ata-2024',
    type: 'diretriz',
    title: 'Guidelines for the treatment of hypothyroidism: prepared by the American Thyroid Association task force on thyroid hormone replacement',
    journal: 'Thyroid',
    year: 2014,
    volume: '24',
    pages: '1670-1751',
    doi: '10.1089/thy.2014.0028',
    authors: ['Jonklaas J', 'Bianco AC', 'Bauer AJ', 'Burman KD', 'Cappola AR', 'Celi FS', 'et al'],
    publisher: 'American Thyroid Association (ATA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25266247/',
    accessDate: '2026-02-14',
    note:
      'RefId mantém “2024” por compatibilidade com o darwin-MFC; guideline ATA amplamente citada foi publicada em 2014 (Thyroid).',
  },
  'ata-hyperthyroidism-2016': {
    id: 'ata-hyperthyroidism-2016',
    type: 'diretriz',
    title:
      '2016 American Thyroid Association Guidelines for Diagnosis and Management of Hyperthyroidism and Other Causes of Thyrotoxicosis',
    journal: 'Thyroid',
    year: 2016,
    volume: '26',
    pages: '1343-1421',
    doi: '10.1089/thy.2016.0229',
    authors: ['Ross DS', 'Burch HB', 'Cooper DS', 'Greenlee MC', 'Laurberg P', 'Maia AL', 'et al'],
    publisher: 'American Thyroid Association (ATA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27521067/',
    accessDate: '2026-02-14',
  },
  'ata-thyroid-nodules-2015': {
    id: 'ata-thyroid-nodules-2015',
    type: 'diretriz',
    title:
      '2015 American Thyroid Association Management Guidelines for Adult Patients with Thyroid Nodules and Differentiated Thyroid Cancer',
    journal: 'Thyroid',
    year: 2016,
    volume: '26',
    pages: '1-133',
    doi: '10.1089/thy.2015.0020',
    authors: ['Haugen BR', 'Alexander EK', 'Bible KC', 'Doherty GM', 'Mandel SJ', 'Nikiforov YE', 'et al'],
    publisher: 'American Thyroid Association (ATA)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26462967/',
    accessDate: '2026-02-14',
  },
  'aap-bronchiolitis-2014': {
    id: 'aap-bronchiolitis-2014',
    type: 'diretriz',
    title: 'Clinical Practice Guideline: The Diagnosis, Management, and Prevention of Bronchiolitis',
    journal: 'Pediatrics',
    year: 2014,
    volume: '134',
    pages: 'e1474-e1502',
    doi: '10.1542/peds.2014-2742',
    authors: ['Ralston SL', 'Lieberthal AS', 'Meissner HC', 'Alverson BK', 'Baley JE', 'Gadomski AM', 'et al'],
    publisher: 'American Academy of Pediatrics (AAP)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25349312/',
    accessDate: '2026-02-14',
  },
  'aap-aom-2013': {
    id: 'aap-aom-2013',
    type: 'diretriz',
    title: 'The Diagnosis and Management of Acute Otitis Media',
    journal: 'Pediatrics',
    year: 2013,
    volume: '131',
    pages: 'e964-e999',
    doi: '10.1542/peds.2012-3488',
    authors: ['Lieberthal AS', 'Carroll AE', 'Chonmaitree T', 'Ganiats TG', 'Hoberman A', 'Jackson MA', 'et al'],
    publisher: 'American Academy of Pediatrics (AAP)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23439909/',
    accessDate: '2026-02-14',
  },
  'espghan-naspghan-constipation-2014': {
    id: 'espghan-naspghan-constipation-2014',
    type: 'diretriz',
    title:
      'Evaluation and Treatment of Functional Constipation in Infants and Children: Evidence-Based Recommendations From ESPGHAN and NASPGHAN',
    journal: 'Journal of Pediatric Gastroenterology and Nutrition',
    year: 2014,
    volume: '58',
    pages: '258-274',
    doi: '10.1097/MPG.0000000000000266',
    authors: ['Tabbers MM', 'DiLorenzo C', 'Berger MY', 'Faure C', 'Langendam MW', 'Nurko S', 'et al'],
    publisher: 'ESPGHAN / NASPGHAN',
    url: 'https://pubmed.ncbi.nlm.nih.gov/24345831/',
    accessDate: '2026-02-14',
  },
  'acg-celiac-2013': {
    id: 'acg-celiac-2013',
    type: 'diretriz',
    title: 'ACG Clinical Guidelines: Diagnosis and Management of Celiac Disease',
    journal: 'The American Journal of Gastroenterology',
    year: 2013,
    volume: '108',
    pages: '656-676',
    doi: '10.1038/ajg.2013.79',
    authors: ['Rubio-Tapia A', 'Hill ID', 'Kelly CP', 'Calderwood AH', 'Murray JA'],
    publisher: 'American College of Gastroenterology (ACG)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/23609613/',
    accessDate: '2026-02-14',
  },
}
