-- ============================================================================
-- ENAMED 2025 Questions with Full Content
-- Generated: 2026-02-02T15:15:24.079239Z
-- Source: Parsed ENAMED 2025 Official Questions
-- ============================================================================

-- Question bank for ENAMED 2025 official microdata
INSERT INTO question_banks (id, name, description, source, year_start, year_end, is_premium)
VALUES (
  'enamed-2025-official',
  'ENAMED 2025 Oficial',
  'Questões oficiais do ENAMED 2025 com parâmetros IRT calibrados e conteúdo completo',
  'official_enamed',
  2025,
  2025,
  FALSE
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW();

-- Insert 20 questions with full content and IRT parameters
INSERT INTO questions (
  id,
  bank_id,
  stem,
  options,
  correct_index,
  area,
  irt_difficulty,
  irt_discrimination,
  irt_guessing,
  irt_infit,
  irt_outfit,
  year,
  validated_by
) VALUES
  (
    'q-enamed-2025-001',
    'enamed-2025-official',
    'Mulher de 58 anos, com diagnóstico de hipertensão arterial sistêmica (HAS) e em tratamento irregular, é encaminhada ao ambulatório de clínica médica de atenção secundária. Queixa-se de fadiga e dispneia aos esforços, com piora progressiva. Ao exame físico, é observado ritmo cardíaco regular em 4 tempos (B3 + B4), sem sopros no precórdio, mas com crépitos em bases pulmonares; pressão arterial: 148 x 90 mmHg. Ecocardiograma transtorácico evidencia hipertrofia ventricular esquerda concêntrica, associada com fração de ejeção de 38% (por Simpson). Exames laboratoriais normais, salvo pela elevação sérica de peptídeo natriurético tipo B (BNP). Para melhorar o controle da HAS e o prognóstico da paciente, o tratamento com inibidor da enzima conversora de angiotensina foi mantido, e o especialista optou por associar determinado fármaco, devido ao impacto positivo no prognóstico de sobrevida dessa paciente. O fármaco introduzido no tratamento da paciente foi',
    '[{"letter": "A", "text": "espironolactona.", "feedback": ""}, {"letter": "B", "text": "clortalidona.", "feedback": ""}, {"letter": "C", "text": "hidralazina.", "feedback": ""}, {"letter": "D", "text": "clonidina.", "feedback": ""}]'::jsonb,
    2,
    'clinica_medica',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-002',
    'enamed-2025-official',
    'Lactente de 4 meses é levado ao serviço de emergência com história de vômitos, poliúria, episódios de fraqueza intensa e febre. Ao exame físico, apresenta-se com desidratação grave e déficit de crescimento significativo. Encontram-se, ainda, sinais radiológicos de osteopenia e raquitismo resistente à vitamina D. Com base na principal hipótese diagnóstica, o distúrbio ácido básico relacionado ao caso é',
    '[{"letter": "A", "text": "alcalose respirat\u00f3ria hipoclor\u00eamica.", "feedback": ""}, {"letter": "B", "text": "acidose metab\u00f3lica hiperclor\u00eamica.", "feedback": ""}, {"letter": "C", "text": "alcalose respirat\u00f3ria hipocal\u00eamica.", "feedback": ""}, {"letter": "D", "text": "acidose metab\u00f3lica hipercal\u00eamica.", "feedback": ""}]'::jsonb,
    1,
    'pediatria',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-003',
    'enamed-2025-official',
    'Homem de 45 anos foi encontrado inconsciente por familiares junto a uma escada de sua casa. Familiares o conduziram em carro próprio, sem medidas-padrão de atendimento pré-hospitalar. Não sabem por quanto tempo ficou desacordado e nem sobre o histórico de saúde. Quando deu entrada no pronto-socorro, encontrava-se inconsciente, com equimose e escoriações na região orbital e palpebral direita, além de escoriações na região cervical posterior e em membros à direita. Não apresentava resposta ao comando verbal, mas respirava espontaneamente com frequência normal. Pressão arterial de 140 x 90 mmHg e pupilas isocóricas. Durante a avaliação, abriu os olhos e começou a se mexer, ainda sem responder a questões ou comandos. Após 30 minutos começou a responder, mas informava não se lembrar de ter caído da escada. Considerando o quadro, a conduta adequada é',
    '[{"letter": "A", "text": "tomografia de cr\u00e2nio, face e coluna cervical; radiografia de membros; manter o paciente em observa\u00e7\u00e3o por 12 horas.", "feedback": ""}, {"letter": "B", "text": "radiografia de cr\u00e2nio, coluna cervical e membros em duas posi\u00e7\u00f5es; internar o paciente para observa\u00e7\u00e3o.", "feedback": ""}, {"letter": "C", "text": "tomografia de cr\u00e2nio, face e radiografia de membros; liberar o paciente para observa\u00e7\u00e3o domiciliar.", "feedback": ""}, {"letter": "D", "text": "radiografia de cr\u00e2nio e face; radiografia de membros; internar o paciente por 24 horas.", "feedback": ""}]'::jsonb,
    1,
    'clinica_medica',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-004',
    'enamed-2025-official',
    'Paciente de 30 anos procurou consultório de ginecologia relatando fadiga, dismenorreia progressiva e dispareunia de profundidade. Toque vaginal: útero de volume normal, retroversofletido, dor à mobilização do colo. Com base nessas informações, a principal hipótese diagnóstica é',
    '[{"letter": "A", "text": "doen\u00e7a inflamat\u00f3ria p\u00e9lvica.", "feedback": ""}, {"letter": "B", "text": "miomatose uterina.", "feedback": ""}, {"letter": "C", "text": "cisto hemorr\u00e1gico.", "feedback": ""}, {"letter": "D", "text": "endometriose.", "feedback": ""}]'::jsonb,
    3,
    'ginecologia_obstetricia',
    -1.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-005',
    'enamed-2025-official',
    'Homem de 28 anos, estudante universitário, residente em zona urbana, comparece à Unidade Básica de Saúde (UBS) referindo aparecimento de lesão cutânea em região dorsal da mão, cerca de 1 mês após ter sofrido arranhadura de gato de rua. A lesão apresenta úlceras com presença de crostas além de nodulações próximas. Foi submetido à biópsia da lesão cutânea e cultura de material. Observou-se dermatite granulomatosa difusa, presença de corpos asteroides e material eosinofílico ao redor de células características. Qual é a principal hipótese diagnóstica e o respectivo tratamento para esse caso?',
    '[{"letter": "A", "text": "Furunculose; cefalexina por 7 dias.", "feedback": ""}, {"letter": "B", "text": "Herpes-zoster; aciclovir por 10 dias.", "feedback": ""}, {"letter": "C", "text": "Esporotricose; itraconazol por 120 dias.", "feedback": ""}, {"letter": "D", "text": "Paracoccidioidomicose; anfotericina B por 30 dias.", "feedback": ""}]'::jsonb,
    0,
    'clinica_medica',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-006',
    'enamed-2025-official',
    'Observe o encaminhamento realizado por um médico de família. “À cardiologia, Encaminho o Sr. J. L. S., de 56 anos, com diagnóstico de cardiopatia isquêmica, que sofreu um infarto agudo do miocárdio há 3 meses. Tem orientação para o uso de antiagregantes plaquetários, mas tem história de úlcera péptica e teve reação alérgica ao clopidogrel e à ticlopidina. Desta forma, solicito orientação quanto à conduta preventiva.” Ao ser assistido pelo cardiologista, o paciente será atendido em qual nível de atenção e receberá que tipo de prevenção, respectivamente?',
    '[{"letter": "A", "text": "Prim\u00e1rio; secund\u00e1rio.", "feedback": ""}, {"letter": "B", "text": "Secund\u00e1rio; secund\u00e1rio.", "feedback": ""}, {"letter": "C", "text": "Terci\u00e1rio; terci\u00e1rio.", "feedback": ""}, {"letter": "D", "text": "Quatern\u00e1rio; terci\u00e1rio.", "feedback": ""}]'::jsonb,
    2,
    'saude_coletiva',
    -1.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-007',
    'enamed-2025-official',
    'Homem de 20 anos, com diagnóstico de esquizofrenia, chega à Unidade de Pronto Atendimento (UPA) acompanhado de familiares, que descrevem que o paciente acordou “torto”. Há 5 dias, foi realizada a troca de risperidona por haloperidol, pois aquela estava em falta na farmácia. Paciente nega outras queixas clínicas. Ao exame, apresenta contratura de região cervical e fácies de dor. Quais são, respectivamente, a hipótese diagnóstica mais provável e a conduta mais adequada?',
    '[{"letter": "A", "text": "Distonia; biperideno intramuscular.", "feedback": ""}, {"letter": "B", "text": "Acatisia; haloperidol intramuscular.", "feedback": ""}, {"letter": "C", "text": "Discinesia tardia; diazepam intramuscular.", "feedback": ""}, {"letter": "D", "text": "S\u00edndrome extrapiramidal; prometazina intramuscular.", "feedback": ""}]'::jsonb,
    1,
    'clinica_medica',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-008',
    'enamed-2025-official',
    'Mulher de 20 anos procura atendimento médico no ambulatório de clínica médica de referência devido a quadro iniciado há 3 meses, com dor e edema articular acometendo articulações das mãos (interfalangeanas proximais, metacarpofalangeanas e punhos), assim como cotovelos, joelhos e tornozelos. Relata rigidez matinal que persiste por mais de 2 horas. O exame físico confirma dor e edema nas articulações descritas, além de mucosas hipocoradas (++/4+), sem outras alterações. A hipótese diagnóstica a ser considerada, o achado laboratorial esperado e a primeira linha de tratamento indicada são, respectivamente,',
    '[{"letter": "A", "text": "esclerose sist\u00eamica; n\u00edveis elevados de creatina quinase; prednisona.", "feedback": ""}, {"letter": "B", "text": "artrite reumatoide; pesquisa de fator reumatoide (FR) positivo; metotrexato.", "feedback": ""}, {"letter": "C", "text": "l\u00fapus eritematoso sist\u00eamico; FAN com padr\u00e3o nuclear pontilhado fino denso; cloroquina.", "feedback": ""}, {"letter": "D", "text": "doen\u00e7a mista do tecido conjuntivo; FAN com padr\u00e3o nuclear pontilhado fino; azatioprina.", "feedback": ""}]'::jsonb,
    1,
    'clinica_medica',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-009',
    'enamed-2025-official',
    'Paciente de 7 anos, na 4ª semana de tratamento quimioterápico para leucemia linfocítica aguda, é admitido em hospital terciário com história de febre há 12 horas (temperatura axilar de 39 °C), tosse e dispneia. Após 24 horas da admissão, segue febril, apesar de ter usado dipirona há 1 hora, e mantém diurese de 2 mL/kg/h. Exame físico: hidratado; pálido; orientado no tempo e no espaço; frequência cardíaca de 130 bpm; temperatura axilar de 39 °C; frequência respiratória de 36 irpm; pressão arterial de 90 x 60 mmHg; boa perfusão periférica; murmúrio vesicular diminuído em base de hemitórax à direita, com crepitações; bulhas taquicárdicas; fígado a 4 cm do rebordo costal direito e 5 cm do apêndice xifoide; baço a 4 cm do rebordo costal esquerdo. Os exames laboratoriais evidenciam lactato aumentado, acidose metabólica e hemograma com leucocitose com desvio à esquerda. Com base no quadro descrito, o diagnóstico é',
    '[{"letter": "A", "text": "sepse.", "feedback": ""}, {"letter": "B", "text": "choque s\u00e9ptico.", "feedback": ""}, {"letter": "C", "text": "disfun\u00e7\u00e3o de m\u00faltiplos \u00f3rg\u00e3os.", "feedback": ""}, {"letter": "D", "text": "s\u00edndrome da resposta inflamat\u00f3ria sist\u00eamica.", "feedback": ""}]'::jsonb,
    2,
    'pediatria',
    1.5,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-010',
    'enamed-2025-official',
    'Paciente feminina de 78 anos, com 24 horas de evolução de dor e abaulamento progressivo em região inguinal direita. Apresentou também alguns episódios de vômitos e diminuição da eliminação de flatos. Antecedentes: neoplasia de mama há 30 anos, diabetes mellitus há 20 anos e tabagista de 40 maços/ano. Ao exame estava normotensa, eucárdica, afebril, eupneica. Índice de massa corporal de 35 kg/m2. Abdome globoso, depressível, com abaulamento não redutível e desconforto à palpação em região inguinal direita, com discreta hiperemia local e sem sinais de irritação peritoneal. Resultados dos exames laboratoriais: [tabela com Hemoglobina 13 g/dL, Leucócitos 10.300/mL, Plaquetas 261.000/mm3, Creatinina 1,8 mg/dL, Ureia 65 mg/dL]. A hipótese diagnóstica mais provável é',
    '[{"letter": "A", "text": "isquemia mesent\u00e9rica.", "feedback": ""}, {"letter": "B", "text": "h\u00e9rnia inguinal indireta.", "feedback": ""}, {"letter": "C", "text": "h\u00e9rnia femoral encarcerada.", "feedback": ""}, {"letter": "D", "text": "neoplasia de c\u00f3lon obstrutiva.", "feedback": ""}]'::jsonb,
    3,
    'cirurgia',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-011',
    'enamed-2025-official',
    'Paciente de 25 anos, com duas gestações e um parto, no segundo trimestre de gestação, compareceu à primeira consulta de pré-natal sem queixas. Após orientações e realização dos testes rápidos, verificou-se que o teste para sífilis foi positivo e imediatamente a paciente recebeu 2,4 milhões UI de penicilina benzatina intramuscular. Paciente nega diagnóstico e tratamento prévios para sífilis. Em relação ao acompanhamento da paciente, é correto afirmar que',
    '[{"letter": "A", "text": "com o tratamento institu\u00eddo, o feto n\u00e3o ter\u00e1 sequelas.", "feedback": ""}, {"letter": "B", "text": "titula\u00e7\u00f5es menores ou iguais a um quarto indicar\u00e3o cicatriz sorol\u00f3gica.", "feedback": ""}, {"letter": "C", "text": "a queda de duas titula\u00e7\u00f5es do VDRL indicar\u00e1 efetividade de tratamento.", "feedback": ""}, {"letter": "D", "text": "o exame de FTA-Abs reagente indicar\u00e1 doen\u00e7a ativa.", "feedback": ""}]'::jsonb,
    1,
    'ginecologia_obstetricia',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-012',
    'enamed-2025-official',
    'Homem de 52 anos, branco, solteiro, comparece à consulta agendada na Unidade Básica de Saúde (UBS) desejando realizar revisão clínica e exames laboratoriais. Desde os 35 anos não faz acompanhamento de saúde. Relata história familiar de diabetes e hipertensão, e a mãe faleceu com câncer de pulmão. Sem história familiar de câncer de próstata. Fuma cerca de 2 maços por dia há 21 anos. Exame físico: pressão arterial de 120 x 80 mmHg, índice de massa corporal de 23 kg/m2, sem outras alterações. Considerando as recomendações de rastreamento para esse paciente, o médico de família e comunidade deve',
    '[{"letter": "A", "text": "solicitar exames de colesterol total e fra\u00e7\u00f5es, hemograma, glicemia de jejum, creatinina, PSA, radiografia de t\u00f3rax, colonoscopia, realizar toque retal; orientar sobre a pr\u00e1tica de atividade f\u00edsica regular.", "feedback": ""}, {"letter": "B", "text": "solicitar exames de colesterol total, glicemia de jejum, pesquisa de sangue oculto nas fezes, PSA, ofertar anti-HIV e HBsAg, realizar toque retal; orientar sobre participa\u00e7\u00e3o no grupo na UBS para abandono do tabagismo.", "feedback": ""}, {"letter": "C", "text": "abordar mudan\u00e7as no estilo de vida e cessa\u00e7\u00e3o do tabagismo; acompanhar, em consultas longitudinais, as futuras possibilidades de exames complementares, quando o paciente atingir faixa et\u00e1ria para investiga\u00e7\u00f5es adicionais.", "feedback": ""}, {"letter": "D", "text": "solicitar exames de colesterol total, HDL e triglicer\u00eddeos, glicemia de jejum, pesquisa de sangue oculto nas fezes, ofertar testes r\u00e1pidos para HIV, s\u00edfilis e hepatites B e C; realizar abordagem sobre possibilidade de cessa\u00e7\u00e3o do tabagismo.", "feedback": ""}]'::jsonb,
    3,
    'saude_coletiva',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-013',
    'enamed-2025-official',
    'Mulher de 32 anos, parda, ensino fundamental incompleto, trabalhadora rural, diarista no plantio de morango, procura Unidade Básica de Saúde (UBS) com queixas de tonturas, dores de cabeça, cansaço, náuseas e falta de ar. Ela referiu que desde os 20 anos sofre com dores de cabeça frequentes, mas há 2 semanas, após uma pulverização de agrotóxicos, começou a apresentar os sintomas descritos. Disse ainda que sua colega de trabalho apresentava queixas similares. Ao ouvir esses relatos, a médica da UBS suspeita de intoxicação aguda por agrotóxicos. Nessa situação, qual é a conduta adequada a ser adotada na assistência?',
    '[{"letter": "A", "text": "Encaminhar como caso suspeito ao centro de refer\u00eancia em sa\u00fade do trabalhador estadual e formalizar den\u00fancia ao Minist\u00e9rio P\u00fablico do Trabalho.", "feedback": ""}, {"letter": "B", "text": "Estabelecer nexo causal entre os sintomas e os resultados de exames complementares, para confirmar diagn\u00f3stico de intoxica\u00e7\u00e3o por agrot\u00f3xicos, e notificar a Vigil\u00e2ncia em Sa\u00fade municipal.", "feedback": ""}, {"letter": "C", "text": "Tratar os sintomas, solicitar exames complementares, notificar o caso no Sistema de Notifica\u00e7\u00e3o de Agravos e Doen\u00e7as (Sinan), conceder atestado m\u00e9dico e solicitar matriciamento \u00e0 Vigil\u00e2ncia em Sa\u00fade do Trabalhador.", "feedback": ""}, {"letter": "D", "text": "Informar n\u00e3o ser respons\u00e1vel pelo preenchimento da comunica\u00e7\u00e3o de acidente de trabalho (CAT), por ser atribui\u00e7\u00e3o exclusiva da medicina do trabalho, no centro municipal de refer\u00eancia em sa\u00fade do trabalhador.", "feedback": ""}]'::jsonb,
    1,
    'saude_coletiva',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-014',
    'enamed-2025-official',
    'Pais de um menino de 10 anos levam a criança para avaliação médica em Unidade Básica de Saúde (UBS). Relatam que seu filho se dá bem com a família até que não lhe seja permitido fazer algo que deseja. Quando isso ocorre, ele fica irritado, impulsivamente agressivo e agitado por várias horas. Assim que se acalma ou consegue o que quer, fica feliz e agradável novamente. Os pais entendem que o filho parece agir deliberadamente para aborrecer os outros e nunca assume a culpa por seus próprios erros ou mau comportamento. Relatam ainda que ele discute com adultos ou figuras de autoridade e em várias situações não aceita as regras de boa convivência com os familiares. Considerando o caso descrito, qual é o diagnóstico mais provável?',
    '[{"letter": "A", "text": "Transtorno afetivo bipolar.", "feedback": ""}, {"letter": "B", "text": "Transtorno de oposi\u00e7\u00e3o desafiante.", "feedback": ""}, {"letter": "C", "text": "Transtorno disruptivo da desregula\u00e7\u00e3o do humor.", "feedback": ""}, {"letter": "D", "text": "Transtorno do d\u00e9ficit de aten\u00e7\u00e3o e hiperatividade.", "feedback": ""}]'::jsonb,
    3,
    'pediatria',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-015',
    'enamed-2025-official',
    'Homem de 50 anos, queixando-se de astenia e constipação com fezes em fita. Há 15 dias, apresenta edema de membros inferiores até a raiz da região crural, bilateralmente, com pouca melhora à elevação dos membros. Ele perdeu 10 kg em 6 meses. Nega hipertensão arterial e diabetes mellitus e não faz uso de medicamento. Os exames do paciente apresentaram os seguintes resultados: [tabela com PA 130x80, Peso 70kg, Ht 35%, Glic 88, Alb 1.8, Cr 1.2, TG 200, Prot 24h 3.6g, Sedimentos prot +++ hem 5/campo]. Dentre esses achados laboratoriais, quais são necessários para a definição da síndrome renal do paciente?',
    '[{"letter": "A", "text": "Prote\u00edna urin\u00e1ria de 24 horas = 3,6 g e albumina s\u00e9rica = 1,8 g/dL.", "feedback": ""}, {"letter": "B", "text": "Prote\u00edna urin\u00e1ria de 24 horas = 3,6 g e triglicer\u00eddeos = 200 mg/dL.", "feedback": ""}, {"letter": "C", "text": "Hemat\u00faria e triglicer\u00eddeos = 200 mg/dL.", "feedback": ""}, {"letter": "D", "text": "Hemat\u00faria e albumina s\u00e9rica = 1,8 g/dL.", "feedback": ""}]'::jsonb,
    1,
    'clinica_medica',
    -1.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-016',
    'enamed-2025-official',
    'Recém-nascido de 15 dias, a termo, Apgar 8/9, peso e comprimento ao nascer de 2.600 g e 46 cm, respectivamente, com síndrome de Down, e cuja gestação não apresentou outras intercorrências. Está na consulta de puericultura com peso e comprimento atuais de 2.900 g e 47 cm, respectivamente. Para o acompanhamento pôndero-estatural, os dados devem ser plotados nas',
    '[{"letter": "A", "text": "curvas de crescimento da OMS desde o nascimento at\u00e9 a adolesc\u00eancia.", "feedback": ""}, {"letter": "B", "text": "curvas de crescimento espec\u00edficas para s\u00edndrome de Down desde o nascimento.", "feedback": ""}, {"letter": "C", "text": "curvas de crescimento da OMS, corrigindo o peso e o comprimento para s\u00edndrome de Down.", "feedback": ""}, {"letter": "D", "text": "curvas de crescimento da OMS at\u00e9 os dois anos e, a partir da\u00ed, em curvas espec\u00edficas para s\u00edndrome de Down.", "feedback": ""}]'::jsonb,
    2,
    'pediatria',
    -1.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-017',
    'enamed-2025-official',
    'Paciente de 20 anos, sexo masculino, vítima de colisão “automóvel a muro”, sem cinto de segurança, é atendido ainda na cena pelo Serviço Móvel de Atendimento de Urgência (SAMU). Exame físico: paciente torporoso; saturação de O2 de 60%, em ar ambiente; frequência respiratória de 28 irpm; frequência cardíaca de 112 bpm; pressão arterial de 90 x 50 mmHg. Desvio da traqueia para a direita, turgência de veias jugulares, hipofonese de bulhas cardíacas e diminuição acentuada do murmúrio vesicular à esquerda. Qual é a conduta adequada no atendimento pré-hospitalar?',
    '[{"letter": "A", "text": "Reposi\u00e7\u00e3o vol\u00eamica.", "feedback": ""}, {"letter": "B", "text": "Cricotireoidostomia.", "feedback": ""}, {"letter": "C", "text": "Pericardiocentese.", "feedback": ""}, {"letter": "D", "text": "Toracocentese.", "feedback": ""}]'::jsonb,
    2,
    'cirurgia',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-018',
    'enamed-2025-official',
    'Paciente de 16 anos comparece ao ambulatório para mostrar os resultados dos exames complementares solicitados na consulta anterior. Está preocupada porque todas as colegas da mesma idade já menstruaram e ela não. O fenótipo é feminino, com pelos pubianos e axilares esparsos. Os exames complementares evidenciam ausência do útero à ultrassonografia pélvica, dosagem sérica do hormônio folículo estimulante (FSH) normal, dosagem de testosterona sérica compatível com níveis do sexo masculino e cariótipo 46 XY. Com base no quadro clínico e nos dados apresentados, a principal hipótese diagnóstica dessa paciente é',
    '[{"letter": "A", "text": "disgenesia gonadal.", "feedback": ""}, {"letter": "B", "text": "malforma\u00e7\u00e3o Mulleriana.", "feedback": ""}, {"letter": "C", "text": "obstru\u00e7\u00e3o do trato genital.", "feedback": ""}, {"letter": "D", "text": "insensibilidade androg\u00eanica.", "feedback": ""}]'::jsonb,
    3,
    'ginecologia_obstetricia',
    1.5,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-019',
    'enamed-2025-official',
    'Mulher de 82 anos, sem história prévia de hipertensão, comparece à consulta preocupada porque aferiu a pressão na farmácia há 1 semana e estava em 146 x 86 mmHg. Em outra aferição, há 2 semanas, na unidade de saúde, a pressão estava em 144 x 88 mmHg. No momento da consulta, a pressão está em 148 x 88 mmHg. Não apresenta sintomas nem está em acompanhamento de outros agravos neste momento. Qual é a abordagem adequada nesse caso?',
    '[{"letter": "A", "text": "Referenciar ao cardiologista para um manejo espec\u00edfico.", "feedback": ""}, {"letter": "B", "text": "Solicitar holter 24 horas e ecocardiograma para ampliar a avalia\u00e7\u00e3o.", "feedback": ""}, {"letter": "C", "text": "Prescrever losartana 50 mg, 1 comprimido \u00e0 noite, com monitoramento da press\u00e3o arterial na unidade.", "feedback": ""}, {"letter": "D", "text": "Realizar uma conduta expectante, sem necessidade de medicamentos, com monitoramento de press\u00e3o arterial na unidade.", "feedback": ""}]'::jsonb,
    3,
    'clinica_medica',
    -1.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  ),
  (
    'q-enamed-2025-020',
    'enamed-2025-official',
    'Mulher travesti de 28 anos, profissional do sexo, comparece à Unidade Básica de Saúde (UBS) em demanda espontânea. Relata relações sexuais frequentes com diferentes parceiros, com uso inconsistente de preservativos, principalmente durante relações anais receptivas. Há 2 dias teve uma relação sexual desprotegida com um cliente que se recusou a usar camisinha. Nunca utilizou medicamento para profilaxia pré-exposição (PrEP) ou pós-exposição (PEP) à infecção pelo HIV. Considerando que a paciente está assintomática no momento, qual a melhor estratégia de prevenção?',
    '[{"letter": "A", "text": "Prescrever PrEP ap\u00f3s resultado n\u00e3o reagente para HIV; indicar PEP ap\u00f3s tratamento inicial e orientar rastreamento de ISTs a cada 3 meses.", "feedback": ""}, {"letter": "B", "text": "Oferecer teste r\u00e1pido para HIV e s\u00edfilis; prescrever PrEP de in\u00edcio imediato; orientar sobre as vacinas dispon\u00edveis no SUS para seu grupo populacional.", "feedback": ""}, {"letter": "C", "text": "Realizar testagem r\u00e1pida para HIV e s\u00edfilis; prescrever PEP mediante resultado n\u00e3o reagente para HIV e programar in\u00edcio da PrEP ap\u00f3s t\u00e9rmino da PEP.", "feedback": ""}, {"letter": "D", "text": "Prescrever PEP e PrEP de forma concomitante; solicitar sorologias para ISTs; agendar retorno para analisar os resultados e revisar ades\u00e3o ao tratamento.", "feedback": ""}]'::jsonb,
    1,
    'saude_coletiva',
    0.0,
    0.891,
    0.25,
    0.8,
    0.9,
    2025,
    NULL
  );

