name: DarwinEducation
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "18.0"
settings:
  base:
    SWIFT_VERSION: 5.10
    PRODUCT_BUNDLE_IDENTIFIER: org.darwineducation.ios
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Darwin Education
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    DARWIN_API_BASE_URL: https://darwinhub.org
    DARWIN_SUPABASE_URL: https://jpzkjkwcoudaxscrukye.supabase.co
    DARWIN_SUPABASE_ANON_KEY: CHANGE_ME
    INFOPLIST_KEY_DarwinAPIBaseURL: $(DARWIN_API_BASE_URL)
    INFOPLIST_KEY_DarwinSupabaseURL: $(DARWIN_SUPABASE_URL)
    INFOPLIST_KEY_DarwinSupabaseAnonKey: $(DARWIN_SUPABASE_ANON_KEY)
targets:
  DarwinEducation:
    type: application
    platform: iOS
    sources:
      - path: DarwinEducation
    resources:
      - path: DarwinEducation/Resources
    settings:
      base:
        PRODUCT_NAME: Darwin Education
